### ISSUE TITLE
Upper-case characters are neglected

### ISSUE THREAD

**Issue by L3viathan** [L3viathan/tischdingsi#1]
Almost all uppercase characters (with a few exceptions) aren't implemented yet (often due to missing characters that could replace them, but sometimes also due to laziness.

**Comment by L3viathan** [comment]
The current mapping only leaves out those upper-case letters that are identical to their flipped version (H, I, N, O, S, X, Z), and the (as far as I know) impossible ones K and R. I'm open to suggestions regarding these, but for now, I view this issue as resolved.

**Comment by fenhl** [comment]
R could become Я.

**Comment by L3viathan** [comment]
No, since this is about 180° rotation, not mirroring.
